name: unit-tests-windows

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-tests:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: |
          C:\Users\runneradmin\.local\bin\poetry install --no-interaction
          C:\Users\runneradmin\.local\bin\poetry run pytest tests
